### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by torsteinpund** [EdvardSire/building-ripes#2]
Når jeg bygger programmet så stopper den på 1 % uten å gi no feilmelding. under følger skript fra terminalen. har forsøkt å kjøre builden flere ganger men endt opp med samme resultat. Noen som vet hva veien videre er?

-- Generating done (0.1s)
-- Build files have been written to: /Users/torstein/ripes-ntnu
[  1%] Automatic MOC and UIC for target CLI_lib
[  1%] Built target CLI_lib_autogen
[  1%] Built target CLI_lib
[  1%] Automatic MOC and UIC for target fancytabbar_lib
[  1%] Built target fancytabbar_lib_autogen
[  1%] Built target fancytabbar_lib
[  1%] Automatic MOC and UIC for target vsrtl_int_lib
[  1%] Built target vsrtl_int_lib_autogen
[  1%] Built target vsrtl_int_lib
[  1%] Automatic MOC and UIC for target vsrtl_gfx_lib
[  1%] Built target vsrtl_gfx_lib_autogen
[  1%] Built target vsrtl_gfx_lib
[  1%] Automatic MOC and UIC for target dwarf++
[  1%] Built target dwarf++_autogen
[  1%] Built target dwarf++
[  1%] Automatic MOC and UIC for target isa_lib
[  1%] Built target isa_lib_autogen
[  1%] Built target isa_lib
[  1%] Automatic MOC and UIC for target cachesim_lib
[  1%] Built target cachesim_lib_autogen
[  1%] Built target cachesim_lib
[  1%] Automatic MOC and UIC for target editor_lib
[  1%] Built target editor_lib_autogen
[  1%] Built target editor_lib
[  1%] Automatic MOC and UIC for target syscall_lib
[  1%] Built target syscall_lib_autogen
[  1%] Built target syscall_lib
[  1%] Automatic MOC and UIC for target assembler_lib
[  1%] Built target assembler_lib_autogen
[  1%] Built target assembler_lib
[  1%] Automatic MOC and UIC for target io_lib
[  1%] Built target io_lib_autogen
[  1%] Built target io_lib
[  1%] Automatic MOC and UIC for target utilities_lib
[  1%] Built target utilities_lib_autogen
[  1%] Built target utilities_lib
[  1%] Generating dummy.cpp
[  1%] Built target version_file
[  1%] Automatic MOC and UIC for target version_lib
[  1%] Built target version_lib_autogen
[  1%] Built target version_lib
[  1%] Automatic MOC and UIC for target ripes_lib
[  1%] Built target ripes_lib_autogen
[  1%] Built target ripes_lib
[  1%] Automatic MOC and UIC for target Ripes
[  1%] Built target Ripes_autogen
[  1%] Built target Ripes
[  1%] Automatic MOC and UIC for target vsrtl_cmp_lib
[  1%] Built target vsrtl_cmp_lib_autogen
[  1%] Built target vsrtl_cmp_lib
[  1%] Automatic MOC and UIC for target vsrtl_core_lib
[  1%] Built target vsrtl_core_lib_autogen
[  1%] Built target vsrtl_core_lib
[  1%] Automatic MOC and UIC for target VSRTL
[  1%] Built target VSRTL_autogen
[  1%] Built target VSRTL
[  1%] Automatic MOC and UIC for target SingleCycleLeros
[  1%] Built target SingleCycleLeros_autogen
[  1%] Built target SingleCycleLeros
[  1%] Automatic MOC and UIC for target tst_adderandreg
[  1%] Built target tst_adderandreg_autogen
[  1%] Built target tst_adderandreg
[  1%] Automatic MOC and UIC for target tst_nestedcomponent
[  1%] Built target tst_nestedcomponent_autogen
[  1%] Built target tst_nestedcomponent
[  1%] Automatic MOC and UIC for target tst_counter
[  1%] Built target tst_counter_autogen
[  1%] Built target tst_counter
[  1%] Automatic MOC and UIC for target tst_rannumgen
[  1%] Built target tst_rannumgen_autogen
[  1%] Built target tst_rannumgen
[  1%] Automatic MOC and UIC for target tst_enumandmux
[  1%] Built target tst_enumandmux_autogen
[  1%] Built target tst_enumandmux
[  1%] Automatic MOC and UIC for target tst_aluandreg
[  1%] Built target tst_aluandreg_autogen
[  1%] Built target tst_aluandreg
[  1%] Automatic MOC and UIC for target tst_registerfile
[  1%] Built target tst_registerfile_autogen
[  1%] Built target tst_registerfile
[  1%] Automatic MOC and UIC for target tst_memory
[  1%] Built target tst_memory_autogen
[  1%] Built target tst_memory
[  1%] Automatic MOC and UIC for target tst_leros
[  1%] Built target tst_leros_autogen
[  1%] Built target tst_leros
[  1%] Automatic MOC and UIC for target elf++
[  1%] Built target elf++_autogen
[  1%] Built target elf++
[  1%] Automatic MOC and UIC for target RISC-V_lib
[  1%] Built target RISC-V_lib_autogen
[  1%] Built target RISC-V_lib
[  1%] Automatic MOC and UIC for target rvss
[  1%] Built target rvss_autogen
[  1%] Built target rvss
[  1%] Automatic MOC and UIC for target rv5s
[  1%] Built target rv5s_autogen
[  1%] Built target rv5s
[  1%] Automatic MOC and UIC for target rv5s_no_fw_hz
[  1%] Built target rv5s_no_fw_hz_autogen
[  1%] Built target rv5s_no_fw_hz
[  1%] Automatic MOC and UIC for target rv5s_no_hz
[  1%] Built target rv5s_no_hz_autogen
[  1%] Built target rv5s_no_hz
[  1%] Automatic MOC and UIC for target rv5s_no_fw
[  1%] Built target rv5s_no_fw_autogen
[  1%] Built target rv5s_no_fw
[  1%] Automatic MOC and UIC for target rv6s_dual
[  1%] Built target rv6s_dual_autogen
[  1%] Built target rv6s_dual

**Comment by EdvardSire** [comment]
Hi! I need the see the entire output, so can you run this command:
```
cd && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/EdvardSire/building-ripes/main/build.sh)" 2>&1 | tee build.log
```
then zip the build log using:
```
cd && zip build.log.zip build.log
```

Then upload the `build.log.zip` here as an attachment so I can have a look:)

**Comment by torsteinpund** [comment]
(base) torstein@dhcp-10-22-69-22 ~ % cd && zip build.log.zip build.log
updating: build.log (deflated 82%)

this comes when i try to zip the build

**Comment by EdvardSire** [comment]
Good, now you should have the the file `/Users/torstein/build.log.zip`.
Attach it here.

**Comment by torsteinpund** [comment]
[build.log.zip](https://github.com/EdvardSire/building-ripes/files/12718363/build.log.zip)

**Comment by EdvardSire** [comment]
Try
```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```
to install rosetta.

and then run:
```
cd && rm -rf ~/ripes-ntnu && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/EdvardSire/building-ripes/main/build.sh)" 2>&1 | tee build.log
```

BTW, this is the underlying issue:
```
WARNING : Caught ImportError, terminating installer workers
ERROR   : dlopen(/Users/torstein/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Users/torstein/Library/Python/3.11/lib/python/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by torsteinpund** [comment]
Tried and got this message

Install of Rosetta 2 finished successfully
(base) torstein@dhcp-10-22-69-22 ~ % cd && rm -rf ~/ripes-ntnu && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/EdvardSire/building-ripes/main/build.sh)" 2>&1 | tee build.log
rm: /Users/torstein/ripes-ntnu/CMakeFiles/Progress/count.txt: Permission denied
rm: /Users/torstein/ripes-ntnu/CMakeFiles/Progress/2: Permission denied
rm: /Users/torstein/ripes-ntnu/CMakeFiles/Progress: Permission denied
rm: /Users/torstein/ripes-ntnu/CMakeFiles: Permission denied
rm: /Users/torstein/ripes-ntnu: Permission denied
(base) torstein@dhcp-10-22-69-22 ~ %

**Comment by EdvardSire** [comment]
Run rm -rf with sudo:
```
cd && sudo rm -rf ~/ripes-ntnu && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/EdvardSire/building-ripes/main/build.sh)" 2>&1 | tee build.log
```

**Comment by torsteinpund** [comment]
I think that worked. the build finished at 100%, but ripes still want open.

**Comment by EdvardSire** [comment]
Does this work:
```
cd && ./ripes-ntnu/Ripes.app/Contents/MacOS/Ripes
```
?

**Comment by torsteinpund** [comment]
Yes!! that worked! Thanks for all the help!!

**Comment by EdvardSire** [comment]
Nice:) The simplest way to open it would be to hit `cmd` and `space` at the same time to bring up Spotlight. Then just type `ripes` and hit enter.
